export const recipes = [
  {
    title: "Chocolate Cake",
    slug: "chocolate-cake",
    category: "dessert",
    description: "Rich and moist chocolate cake",
    ingredients: ["Flour", "Sugar", "Cocoa", "Eggs", "Butter"],
    steps: ["Preheat oven", "Mix ingredients", "Bake for 30 minutes"],
  },
  {
    title: "Tomato Soup",
    slug: "tomato-soup",
    category: "soup",
    description: "Simple and delicious tomato soup",
    ingredients: ["Tomatoes", "Garlic", "Onion", "Basil"],
    steps: ["Blend ingredients", "Boil", "Serve hot"],
  },
  {
    title: "Caesar Salad",
    slug: "caesar-salad",
    category: "salad",
    description: "Classic Caesar with crispy croutons",
    ingredients: ["Lettuce", "Croutons", "Parmesan", "Caesar dressing"],
    steps: ["Chop lettuce", "Add dressing", "Top with croutons and cheese"],
  },
  {
    title: "Grilled Chicken",
    slug: "grilled-chicken",
    category: "main",
    description: "Juicy chicken breast with spices",
    ingredients: ["Chicken breast", "Olive oil", "Garlic", "Paprika"],
    steps: ["Marinate chicken", "Grill for 15 minutes", "Serve hot"],
  },
  {
    title: "Margarita Pizza",
    slug: "margarita-pizza",
    category: "main",
    description: "Thin crust pizza with tomato and cheese",
    ingredients: ["Pizza dough", "Tomato sauce", "Mozzarella", "Basil"],
    steps: ["Spread sauce", "Add cheese", "Bake until golden"],
  },
  {
    title: "Fruit Smoothie",
    slug: "fruit-smoothie",
    category: "drink",
    description: "Healthy and refreshing smoothie",
    ingredients: ["Banana", "Strawberries", "Yogurt", "Honey"],
    steps: ["Blend all ingredients", "Serve chilled"],
  },
  {
    title: "Beef Stroganoff",
    slug: "beef-stroganoff",
    category: "main",
    description: "Creamy Russian beef dish",
    ingredients: ["Beef", "Mushrooms", "Onion", "Sour cream"],
    steps: ["Fry beef", "Add mushrooms and onion", "Mix with sour cream"],
  },
  {
    title: "Pancakes",
    slug: "pancakes",
    category: "dessert",
    description: "Fluffy pancakes with syrup",
    ingredients: ["Flour", "Milk", "Eggs", "Baking powder", "Sugar"],
    steps: ["Mix ingredients", "Cook on skillet", "Serve with syrup"],
  },
  {
    title: "Greek Salad",
    slug: "greek-salad",
    category: "salad",
    description: "Fresh salad with feta cheese",
    ingredients: ["Tomatoes", "Cucumber", "Feta", "Olives", "Onion"],
    steps: ["Chop veggies", "Add feta and olives", "Drizzle with olive oil"],
  },
  {
    title: "Lemonade",
    slug: "lemonade",
    category: "drink",
    description: "Refreshing summer lemonade",
    ingredients: ["Lemons", "Sugar", "Water", "Ice"],
    steps: ["Squeeze lemons", "Mix with sugar and water", "Add ice and serve"],
  },
];
